import { cn } from "@/lib/utils";
import { bundledLanguages, createHighlighter, Highlighter } from 'shiki';

// Cache the highlighter instance for performance.
let highlighter: Highlighter | null = null;
async function getHighlighter() {
    if (!highlighter) {
        // Load the themes and languages you need.
        highlighter = await createHighlighter({
            themes: ['github-light', 'github-dark'],
            langs: Object.keys(bundledLanguages),
        });
    }
    return highlighter;
}

interface CodeBlockProps {
  // The raw code string to be highlighted.
  code: string;
  // The language for syntax highlighting (e.g., 'javascript', 'python').
  language?: string;
  // Optional additional class names for styling.
  className?: string;
}

/**
 * CodeBlock is an asynchronous server component that renders syntax-highlighted code.
 * It uses the 'shiki' library to generate themed and highlighted HTML.
 */
export async function CodeBlock({ code, language, className }: CodeBlockProps) {
  const shikiHighlighter = await getHighlighter();

  // Determine the language for highlighting, defaulting to plain text ('txt').
  const lang = language && language !== 'undefined' ? language : 'txt';

  // The database might store newline characters as escaped strings (e.g., '\\n').
  // This replacement ensures they are converted to actual newlines for proper rendering.
  const codeWithNewlines = code.replace(/\\n/g, '\n');

  let highlightedHtml = '';
  try {
    // Convert the raw code string into highlighted HTML.
    highlightedHtml = shikiHighlighter.codeToHtml(codeWithNewlines, {
      lang,
      themes: { light: 'github-light', dark: 'github-dark' },
    });
  } catch (error) {
    console.error(`Shiki highlighting failed for lang: '${lang}'`, error);
    // If highlighting fails, fall back to a simple, un-highlighted code block.
    const escapedCode = codeWithNewlines.replace(/[&<>'"`]/g, (char) => ({
        '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;', '`': '&#96;'
    }[char]!));
    highlightedHtml = `<pre class="shiki-fallback"><code>${escapedCode}</code></pre>`;
  }

  return (
    <div className={cn("relative code-block-container", className)}>
      {/* Render the HTML generated by Shiki */}
      <div dangerouslySetInnerHTML={{ __html: highlightedHtml }} />
      
      {/* Display the language name if it's not plain text */}
      {lang !== 'txt' && (
        <div className="absolute top-2 right-2 text-xs text-muted-foreground bg-background/50 px-2 py-1 rounded-md select-none">
          {lang}
        </div>
      )}
    </div>
  );
}
